"""initial schema

Revision ID: 0cb0834225c8
Revises: 
Create Date: 2026-08-20 20:54:33.416666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb0834225c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.Enum("RM", "MANAGER", "ADMIN", name="roleenum"), nullable=False),
        sa.Column("manager_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["manager_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "source_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_customer_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("pan_like", sa.String(length=64), nullable=True),
        sa.Column("mobile", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("dob", sa.DateTime(), nullable=True),
        sa.Column("product_holdings", sa.JSON(), nullable=True),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "source_customer_id", name="uix_source_system_customer"),
    )
    op.create_index("ix_source_records_pan_like", "source_records", ["pan_like"], unique=False)
    op.create_index("ix_source_records_mobile", "source_records", ["mobile"], unique=False)
    op.create_index("ix_source_records_email", "source_records", ["email"], unique=False)

    op.create_table(
        "golden_customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("primary_name", sa.String(length=256), nullable=False),
        sa.Column("pan_like", sa.String(length=64), nullable=True),
        sa.Column("mobile", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("dob", sa.DateTime(), nullable=True),
        sa.Column("relationship_value", sa.Float(), nullable=True),
        sa.Column("rm_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["rm_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_golden_customers_pan_like", "golden_customers", ["pan_like"], unique=False)
    op.create_index("ix_golden_customers_mobile", "golden_customers", ["mobile"], unique=False)
    op.create_index("ix_golden_customers_email", "golden_customers", ["email"], unique=False)

    op.create_table(
        "customer_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("golden_customer_id", sa.Integer(), nullable=False),
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("match_type", sa.Enum("DETERMINISTIC", "PROBABILISTIC", name="matchtypeenum"), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("match_reasons", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["golden_customer_id"], ["golden_customers.id"]),
        sa.ForeignKeyConstraint(["source_record_id"], ["source_records.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "field_provenances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("golden_customer_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=True),
        sa.Column("source_system", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=True),
        sa.Column("resolution_method", sa.Enum("SOURCE_PRECEDENCE", "MANUAL", name="resolutionmethodenum"), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["golden_customer_id"], ["golden_customers.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "review_queue_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("golden_customer_id", sa.Integer(), nullable=True),
        sa.Column("candidate_source_record_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.Column("status", sa.Enum("PENDING", "RESOLVED", "REJECTED", name="reviewstatusenum"), nullable=False),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["candidate_source_record_id"], ["source_records.id"]),
        sa.ForeignKeyConstraint(["golden_customer_id"], ["golden_customers.id"]),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("golden_customer_id", sa.Integer(), nullable=False),
        sa.Column("product_type", sa.String(length=128), nullable=False),
        sa.Column("eligibility_passed", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("score_breakdown", sa.JSON(), nullable=True),
        sa.Column("reason_text", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["golden_customer_id"], ["golden_customers.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "config_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.Enum("MATCH_WEIGHTS", "THRESHOLDS", "SOURCE_PRECEDENCE", "ELIGIBILITY_RULES", "SCORING_WEIGHTS", "REVIEW_RULES", "NORMALIZATION_RULES", name="configcategoryenum"), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category", "key", name="uix_config_category_key"),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=128), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=True),
        sa.Column("before_value", sa.JSON(), nullable=True),
        sa.Column("after_value", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_logs")
    op.drop_table("config_entries")
    op.drop_table("opportunities")
    op.drop_table("review_queue_items")
    op.drop_table("field_provenances")
    op.drop_table("customer_links")
    op.drop_index("ix_golden_customers_email", table_name="golden_customers")
    op.drop_index("ix_golden_customers_mobile", table_name="golden_customers")
    op.drop_index("ix_golden_customers_pan_like", table_name="golden_customers")
    op.drop_table("golden_customers")
    op.drop_index("ix_source_records_email", table_name="source_records")
    op.drop_index("ix_source_records_mobile", table_name="source_records")
    op.drop_index("ix_source_records_pan_like", table_name="source_records")
    op.drop_table("source_records")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
